# Set true color
set-option -sa terminal-overrides ",xterm*:Tc"

# Enable mouse support
set -g mouse on

# Change indexing to start from 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Set prefix btn
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Shigt-Alt {h,j} to navigate windows
bind -n M-K previous-window
bind -n M-J next-window

set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tpm'

set -g @catppuccin_flavor 'frappe'
set -g status-left " TMUX [S: #S] "
set -g status-left-length 100
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_default_text " #W"
set -g @catppuccin_window_current_text " #W"
set -g status-right '#[fg=#{@thm_crust},bg=#{@thm_teal}] %H:%M %d/%m/%Y '
set -g status-right-length 100

run '~/.tmux/plugins/tpm/tpm'

# set vi mode
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

bind "'" split-window -v -c "#{pane_current_path}"
bind ";" split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
